In [106]:
# !pip install selenium
# !pip install openpyxl
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
import time

In [ ]:
driver = webdriver.Chrome()

driver.maximize_window()

# explicit wait

wait = WebDriverWait(driver, 25)

# function to check if webpage is fully loaded 

def wait_for_page_to_load(driver, wait):
    # web for the webpage to load 
    # page_title=driver.title
    try: 
        # wait.until(
        #     lambda d: d.execute_script("return document.readyState") != "complete"
        #     )

        wait.until(
            lambda d: d.execute_script("return document.readyState") == "complete"
            )
    except:
        page_title = driver.title
        print(f"The page \"{page_title}\" did not get fully loaded within the given duration.\n")
    else:
        page_title = driver.title
        print(f"The page is \"{page_title}\" fully loaded.\n")


url = "https://finance.yahoo.com/"
driver.get(url)

wait_for_page_to_load(driver,wait)

# hovering on Markets menu
actions = ActionChains(driver)
markets_menu = wait.until(
    ec.presence_of_element_located((By.XPATH, "/html/body/div[1]/header/div/nav/ol/li[3]/a/div"))
)
actions.move_to_element(markets_menu).perform()

# hovering on stocks 
# actions = ActionChains(driver)
stocks_menu = wait.until(
    ec.presence_of_element_located((By.XPATH, "/html/body/div[1]/header/div/nav/ol/li[3]/ol/li[1]/a/span"))
)
actions.move_to_element(stocks_menu).perform()

# click on trending 
trending = wait.until(
    ec.element_to_be_clickable((By.XPATH, "/html/body/div[1]/header/div/nav/ol/li[3]/ol/li[1]/ol/li[4]/a/span"))
)
trending.click()

# temporary add and it is right
time.sleep(5)

wait_for_page_to_load(driver,wait)


# click on most active
most_active = wait.until(
    ec.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[1]/div[4]/main[1]/section[1]/section[1]/section[1]/section[1]/section[1]/div[1]/div[1]/div[1]/a[1]"))
)
most_active.click()

# temporary add and it is right
time.sleep(5)

wait_for_page_to_load(driver,wait)




# scraping the data 
data=[]
while True:
    # scraping 
    wait.until(
        ec.presence_of_all_elements_located((By.TAG_NAME, "table"))
    )
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    time.sleep(5)
    # print(len(rows))
    
    for row in rows:
        values = row.find_elements(By.TAG_NAME, "td")
        # time.sleep(5)
        print([val.text for val in values])
        stock = {
            "name": values[1].text,
            "symbol": values[0].text,
            "price": values[3].text,
            "change": values[4].text,
            "volume": values[6].text,
            "market_cap": values[8].text,
            "pe_ratio": values[9].text
        }
        
        data.append(stock)

    
    # click next 
    try:
        next_button=wait.until(
            ec.element_to_be_clickable((By.XPATH, "/html/body/div[1]/div[4]/main/section/section/section/section/section[1]/div/div[4]/div[3]/button[3]"))
            )
    except: 
        print("The 'next' button is not clickable. We have navigated through all the pages.")
        break
    else:
        next_button.click() 
        time.sleep(5)
        
driver.quit()

The page is "Yahoo Finance - Stock Market Live, Quotes, Business & Finance News" fully loaded..

The page is "Top Trending Stocks: US stocks with the highest interest today - Yahoo Finance" fully loaded..

The page is "Most Active Stocks: US stocks with the highest trading volume today - Yahoo Finance" fully loaded..

['NU', 'Nu Holdings Ltd.', '', '13.99', '+0.32', '+2.34%', '152.753M', '56.67M', '67.578B', '21.09', '+0.96%', '11.20\n18.98']
['AAL', 'American Airlines Group Inc.', '', '15.67', '-0.64', '-3.92%', '133.164M', '97.279M', '10.364B', '53.33', '+34.02%', '10.09\n18.79']
['SKHYV', 'SK hynix Inc.', '', '168.01', '+168.01', '0.00%', '107.675M', '82.102M', '1.193T', '--', '-8.63%', '151.30\n177.00']
['ONDS', 'Ondas Inc.', '', '7.36', '+0.40', '+5.75%', '103.149M', '71.394M', '4.194B', '15.91', '+203.93%', '1.78\n15.28']
['NVDA', 'NVIDIA Corporation', '', '211.80', '+8.27', '+4.06%', '102.209M', '158.655M', '5.13T', '31.17', '+19.23%', '164.07\n236.54']
['OPEN', 'Opendoor Technologies Inc.', '', '4.55', '+0.07', '+1.45%', '98.083M', '48.965M', '4.39B', '--', '+331.25%', '0.95\n10.87']
['NOK', 'Nokia Oyj', '', '11.70', '+0.01', '+0.09%', '87.515M', '110.585M', '65.316B', '76.29', '+146.11%', '4.00\n17.45']
['PATH', 'UiPath, Inc.', '', '11.94', '+0.09', '+0.76%', '85.807M', '44.753M', '6.186B', '19.60', '-4.28%', '9.20\n19.84']
['SOFI', 'SoFi Technologies, Inc.', '', '18.55', '+0.42', '+2.32%', '84.128M', '76.151M', '23.795B', '40.75', '-13.50%', '14.92\n32.73']
['INTC', 'Intel Corporation', '', '107.76', '+4.64', '+4.50%', '81.729M', '134.396M', '541.602B', '--', '+349.91%', '18.97\n142.35']
['CLSK', 'CleanSpark, Inc.', '', '13.45', '+1.09', '+8.82%', '74.001M', '21.268M', '3.451B', '--', '+1.39%', '8.00\n23.61']
['IBM', 'International Business Machines Corporation', '', '217.07', '-73.16', '-25.21%', '67.423M', '9.114M', '204.021B', '25.71', '+2.66%', '212.34\n332.46']
['SKHY', 'SK hynix Inc.', '', '193.92', '+41.57', '+27.29%', '66.814M', '82.102M', '1.377T', '--', '-8.63%', '151.30\n177.00']
['WULF', 'TeraWulf Inc.', '', '19.41', '-1.48', '-7.08%', '57.849M', '31.56M', '9.618B', '--', '+328.95%', '4.64\n29.84']
['MARA', 'MARA Holdings, Inc.', '', '12.16', '-0.03', '-0.25%', '57.195M', '43.299M', '4.636B', '--', '-35.02%', '6.66\n23.45']
['T', 'AT&T Inc.', '', '21.28', '-0.27', '-1.25%', '53.555M', '51.485M', '147.861B', '7.20', '-20.24%', '19.89\n29.79']
['ORCL', 'Oracle Corporation', '', '127.94', '-3.60', '-2.74%', '52.648M', '29.642M', '368.527B', '22.56', '-44.02%', '131.35\n345.72']
['BMNR', 'Bitmine Immersion Technologies, Inc.', '', '16.29', '+1.68', '+11.50%', '51.549M', '37.397M', '9.278B', '--', '-63.44%', '12.80\n71.74']
['BAC', 'Bank of America Corporation', '', '60.62', '+1.12', '+1.88%', '49.432M', '35.823M', '430.195B', '--', '+28.93%', '44.75\n60.83']
['JOBY', 'Joby Aviation, Inc.', '', '7.89', '+0.41', '+5.48%', '49.054M', '35.566M', '7.761B', '--', '-46.38%', '7.43\n20.95']
['PLTR', 'Palantir Technologies Inc.', '', '133.72', '+3.68', '+2.83%', '45.485M', '43.204M', '320.569B', '146.18', '-12.48%', '106.37\n207.52']
['SPCX', 'Space Exploration Technologies Corp.', '', '136.08', '-3.06', '-2.20%', '43.495M', '143.353M', '1.793T', '--', '-13.55%', '136.78\n225.64']
['F', 'Ford Motor Company', '', '13.94', '+0.09', '+0.65%', '42.722M', '60.816M', '55.547B', '--', '+19.71%', '10.68\n17.78']
['BBD', 'Banco Bradesco S.A.', '', '3.63', '+0.02', '+0.55%', '42.618M', '31.184M', '38.372B', '8.54', '+23.63%', '2.73\n4.30']
['PFE', 'Pfizer Inc.', '', '24.25', '-0.23', '-0.94%', '40.862M', '40.481M', '138.212B', '18.68', '-0.53%', '23.11\n28.75']
['PLUG', 'Plug Power Inc.', '', '2.27', '+0.10', '+4.61%', '40.712M', '71.696M', '3.167B', '--', '+41.83%', '1.39\n4.58']
['ERIC', 'Telefonaktiebolaget LM Ericsson (publ)', '', '10.14', '-1.58', '-13.48%', '39.448M', '11.075M', '33.48B', '--', '+62.33%', '7.16\n13.77']
['WFC', 'Wells Fargo & Company', '', '85.29', '-2.38', '-2.71%', '38.943M', '16.369M', '261.004B', '--', '+11.17%', '72.78\n97.76']
['RIG', 'Transocean Ltd.', '', '5.31', '-0.06', '-1.12%', '37.61M', '35.194M', '5.877B', '--', '+103.41%', '2.53\n7.66']
['IREN', 'IREN Limited', '', '38.59', '-0.39', '-1.00%', '34.939M', '46.424M', '13.791B', '71.76', '+130.92%', '14.72\n76.87']
['AAPL', 'Apple Inc.', '', '314.86', '-2.45', '-0.77%', '34.499M', '54.599M', '4.624T', '38.47', '+51.74%', '201.50\n323.45']
['FIG', 'Figma, Inc.', '', '23.86', '+0.21', '+0.89%', '33.219M', '21.018M', '12.607B', '--', '-79.52%', '16.60\n142.92']
['SOUN', 'SoundHound AI, Inc.', '', '6.69', '+0.20', '+3.08%', '32.492M', '29.322M', '2.915B', '--', '-42.57%', '5.83\n22.17']
['C', 'Citigroup Inc.', '', '133.27', '-7.44', '-5.29%', '32.124M', '11.971M', '227.302B', '--', '+55.10%', '87.94\n147.96']
['GRAB', 'Grab Holdings Limited', '', '3.80', '-0.14', '-3.55%', '31.802M', '52.096M', '15.542B', '101.30', '-21.83%', '3.18\n6.62']
['MU', 'Micron Technology, Inc.', '', '983.12', '+46.12', '+4.92%', '30.387M', '51.167M', '1.11T', '21.15', '+680.12%', '103.38\n1,255.00']
['HL', 'Hecla Mining Company', '', '15.50', '+0.25', '+1.64%', '30.188M', '21.146M', '10.396B', '22.17', '+149.59%', '5.62\n34.17']
['SNAP', 'Snap Inc.', '', '4.68', '+0.02', '+0.43%', '29.933M', '46.291M', '7.756B', '--', '-50.84%', '3.81\n10.41']
['CPNG', 'Coupang, Inc.', '', '17.74', '-0.18', '-1.00%', '29.012M', '23.934M', '31.844B', '--', '-42.43%', '14.92\n34.08']
['NFLX', 'Netflix, Inc.', '', '73.53', '-0.30', '-0.41%', '28.473M', '42.403M', '309.62B', '23.85', '-41.42%', '70.86\n127.75']
['ACHR', 'Archer Aviation Inc.', '', '4.85', '+0.30', '+6.59%', '28.414M', '42.02M', '3.7B', '--', '-59.59%', '4.51\n14.62']
['QXO', 'QXO, Inc.', '', '14.46', '+0.57', '+4.10%', '28.16M', '21.703M', '15.007B', '--', '-34.33%', '13.82\n27.61']
['MSFT', 'Microsoft Corporation', '', '384.93', '-6.06', '-1.55%', '26.895M', '40.025M', '2.859T', '23.29', '-22.70%', '349.20\n555.45']
['RIVN', 'Rivian Automotive, Inc.', '', '17.50', '+0.19', '+1.10%', '26.701M', '34.644M', '25.329B', '--', '+37.05%', '11.57\n22.69']
['RKT', 'Rocket Companies, Inc.', '', '14.30', '+0.39', '+2.80%', '26.585M', '28.061M', '40.461B', '547.98', '+4.51%', '12.17\n24.36']
['CMCSA', 'Comcast Corporation', '', '23.19', '-0.78', '-3.25%', '26.067M', '35.83M', '82.84B', '4.68', '-26.34%', '22.13\n33.76']
['STLA', 'Stellantis N.V.', '', '5.69', '+0.12', '+2.15%', '24.798M', '18.476M', '16.487B', '--', '-41.31%', '5.25\n12.22']
['DNN', 'Denison Mines Corp.', '', '3.17', '+0.14', '+4.62%', '24.736M', '23.945M', '2.869B', '--', '+62.03%', '1.79\n4.43']
['KEEL', 'Keel Infrastructure Corp.', '', '4.49', '+0.13', '+2.98%', '24.573M', '45.352M', '2.711B', '--', '+327.45%', '1.01\n7.37']
['SMR', 'NuScale Power Corporation', '', '8.60', '+0.25', '+2.99%', '24.042M', '35.831M', '2.977B', '--', '-80.57%', '8.27\n57.42']
['VALE', 'Vale S.A.', '', '14.59', '+0.41', '+2.89%', '23.954M', '23.633M', '62.092B', '19.96', '+46.34%', '9.36\n17.94']
['INFY', 'Infosys Limited', '', '11.05', '-0.45', '-3.91%', '23.875M', '19.766M', '44.741B', '14.40', '-36.88%', '10.34\n30.00']
['AMZN', 'Amazon.com, Inc.', '', '247.49', '+0.18', '+0.07%', '23.406M', '49.665M', '2.662T', '29.58', '+9.26%', '196.00\n278.56']
['NOW', 'ServiceNow, Inc.', '', '104.85', '-6.41', '-5.76%', '23.21M', '28.441M', '108.133B', '66.23', '-41.87%', '81.24\n210.20']
['NIO', 'NIO Inc.', '', '5.01', '+0.08', '+1.62%', '23.114M', '34.093M', '12.553B', '--', '+16.00%', '3.96\n8.02']
['TSLA', 'Tesla, Inc.', '', '396.18', '+1.42', '+0.36%', '22.671M', '52.702M', '1.488T', '362.40', '+27.02%', '297.82\n498.83']
['BB', 'BlackBerry Limited', '', '11.01', '+0.30', '+2.80%', '22.239M', '34.363M', '6.453B', '110.55', '+163.14%', '3.12\n13.59']
['SMCI', 'Super Micro Computer, Inc.', '', '27.65', '-0.01', '-0.04%', '21.898M', '50.903M', '17.886B', '14.50', '-47.98%', '19.48\n62.36']
['WBD', 'Warner Bros. Discovery, Inc.', '', '27.48', '+0.39', '+1.44%', '21.76M', '20.055M', '68.896B', '--', '+125.19%', '10.76\n30.00']
['CSCO', 'Cisco Systems, Inc.', '', '117.09', '-2.16', '-1.81%', '21.344M', '24.761M', '461.503B', '39.75', '+77.51%', '65.75\n130.37']
['FAST', 'Fastenal Company', '', '45.74', '-1.31', '-2.78%', '20.524M', '7.081M', '52.511B', '--', '+4.25%', '38.97\n50.63']
['AUR', 'Aurora Innovation, Inc.', '', '6.13', '+0.08', '+1.32%', '20.422M', '29.719M', '12.022B', '--', '+4.49%', '3.60\n8.57']
['WIT', 'Wipro Limited', '', '1.84', '-0.06', '-3.16%', '20.365M', '12.785M', '18.201B', '14.20', '-34.48%', '1.80\n3.12']
['BTE', 'Baytex Energy Corp.', '', '4.24', '+0.03', '+0.71%', '20.201M', '20.307M', '3.021B', '--', '+123.94%', '1.81\n5.36']
['BSX', 'Boston Scientific Corporation', '', '42.63', '-2.02', '-4.52%', '20.088M', '20.701M', '63.363B', '18.68', '-56.85%', '42.25\n109.50']
['MRVL', 'Marvell Technology, Inc.', '', '222.44', '+4.91', '+2.26%', '20.012M', '42.532M', '199.65B', '75.14', '+200.41%', '61.44\n329.88']
['CRWV', 'CoreWeave, Inc.', '', '79.94', '-3.37', '-4.05%', '19.758M', '29.225M', '43.613B', '--', '-40.74%', '63.80\n153.20']
['KVUE', 'Kenvue Inc.', '', '18.76', '-0.47', '-2.44%', '19.474M', '20.116M', '36.019B', '22.89', '-10.10%', '14.02\n22.87']
['FRMI', 'Fermi Inc.', '', '6.74', '+0.43', '+6.81%', '19.241M', '19.856M', '4.301B', '--', '-80.60%', '4.47\n36.99']
['QS', 'QuantumScape Corporation', '', '6.42', '+0.14', '+2.23%', '19.138M', '25.934M', '3.949B', '--', '-42.12%', '5.90\n19.07']
['HPQ', 'HP Inc.', '', '24.63', '-0.14', '-0.57%', '18.983M', '18.763M', '22.525B', '9.15', '+1.02%', '17.56\n29.65']
['AMD', 'Advanced Micro Devices, Inc.', '', '548.13', '+13.74', '+2.57%', '18.876M', '36.625M', '893.781B', '178.20', '+243.42%', '149.22\n584.73']
['CIFR', 'Cipher Digital Inc.', '', '19.87', '-0.22', '-1.07%', '18.875M', '25.318M', '8.128B', '--', '+236.43%', '4.55\n30.14']
['UBER', 'Uber Technologies, Inc.', '', '72.08', '-2.18', '-2.94%', '18.702M', '19.436M', '146.726B', '18.36', '-19.47%', '67.19\n101.99']
['BTG', 'B2Gold Corp.', '', '3.79', '+0.01', '+0.26%', '18.631M', '26.75M', '5.05B', '10.07', '+9.57%', '3.31\n6.29']
['UGP', 'Ultrapar Participações S.A.', '', '5.94', '-0.06', '-1.00%', '18.324M', '3.036M', '6.349B', '10.53', '+99.34%', '2.80\n6.20']
['RGTI', 'Rigetti Computing, Inc.', '', '16.11', '+0.75', '+4.88%', '18.272M', '41.652M', '5.355B', '--', '+20.75%', '12.48\n58.15']
['LYG', 'Lloyds Banking Group plc', '', '5.93', '+0.04', '+0.68%', '18.218M', '21.608M', '86.168B', '14.53', '+44.01%', '4.05\n6.34']
['ABEV', 'Ambev S.A.', '', '3.09', '+0.03', '+0.98%', '18.134M', '27.228M', '47.749B', '15.92', '+30.21%', '2.10\n3.45']
['MSTR', 'Strategy Inc', '', '97.58', '+5.48', '+5.95%', '17.706M', '21.431M', '35.381B', '--', '-79.18%', '81.81\n457.22']
['CMG', 'Chipotle Mexican Grill, Inc.', '', '36.43', '-0.20', '-0.55%', '17.566M', '19.185M', '46.73B', '33.57', '-32.10%', '28.04\n55.14']
['VZ', 'Verizon Communications Inc.', '', '42.47', '-0.21', '-0.49%', '17.515M', '26.984M', '177.336B', '10.39', '+3.44%', '38.39\n51.68']
['IONQ', 'IonQ, Inc.', '', '39.29', '+0.41', '+1.05%', '17.283M', '31.583M', '14.666B', '42.20', '-6.25%', '25.89\n84.64']
['HPE', 'Hewlett Packard Enterprise Company', '', '49.56', '+2.32', '+4.91%', '17.133M', '25.912M', '65.628B', '44.08', '+132.94%', '19.64\n64.25']
['CAG', 'Conagra Brands, Inc.', '', '14.15', '-0.18', '-1.26%', '16.852M', '17.414M', '6.77B', '--', '-24.58%', '12.53\n20.32']
['CDE', 'Coeur Mining, Inc.', '', '16.00', '+0.41', '+2.63%', '16.67M', '29.275M', '16.489B', '12.89', '+70.38%', '8.57\n27.77']
['NBIS', 'Nebius Group N.V.', '', '194.09', '-16.42', '-7.80%', '16.577M', '17.318M', '49.279B', '72.79', '+293.26%', '49.00\n299.86']
['HOOD', 'Robinhood Markets, Inc.', '', '113.45', '+3.59', '+3.27%', '16.257M', '31.131M', '102.162B', '53.35', '+10.37%', '63.52\n153.86']
['XOM', 'ExxonMobil Holdings Corporation', '', '145.09', '+0.58', '+0.40%', '16.096M', '17.201M', '601.39B', '24.33', '+27.99%', '105.53\n176.41']
['APLD', 'Applied Digital Corporation', '', '28.47', '-0.37', '-1.28%', '16.021M', '21.915M', '8.136B', '--', '+189.27%', '9.60\n50.73']
['CRCL', 'Circle Internet Group', '', '63.22', '+0.22', '+0.35%', '15.793M', '14.995M', '15.715B', '--', '-67.75%', '49.90\n262.97']
['QBTS', 'D-Wave Quantum Inc.', '', '18.95', '+0.29', '+1.55%', '15.664M', '35.104M', '7.02B', '--', '+15.54%', '12.75\n46.75']
['CPRX', 'Catalyst Pharmaceuticals, Inc.', '', '31.49', '+0.01', '+0.03%', '15.514M', '2.428M', '3.855B', '18.20', '+50.26%', '19.05\n32.56']
['HBAN', 'Huntington Bancshares Incorporated', '', '17.85', '-0.08', '-0.45%', '14.903M', '21.569M', '36.184B', '13.99', '+8.27%', '14.89\n19.46']
['ITUB', 'Itaú Unibanco Holding S.A.', '', '8.55', '+0.08', '+0.94%', '14.811M', '22.645M', '94.237B', '10.57', '+38.70%', '5.93\n9.60']
['PCG', 'PG&E Corporation', '', '17.44', '+0.07', '+0.40%', '14.8M', '19.369M', '38.407B', '13.48', '+33.62%', '12.97\n19.16']
['WMT', 'Walmart Inc.', '', '113.70', '-1.08', '-0.94%', '14.682M', '22.071M', '904.834B', '40.41', '+20.33%', '94.43\n135.16']
['JPM', 'JPMorgan Chase & Co.', '', '342.89', '+8.36', '+2.50%', '14.537M', '9.195M', '918.778B', '--', '+16.74%', '279.10\n343.45']
['KDP', 'Keurig Dr Pepper Inc.', '', '30.26', '-0.99', '-3.17%', '14.47M', '13.719M', '41.171B', '23.18', '-4.55%', '24.88\n35.94']
['AGNC', 'AGNC Investment Corp.', '', '11.18', '+0.19', '+1.73%', '14.373M', '15.23M', '12.834B', '9.11', '+19.46%', '9.12\n12.19']
['TSM', 'Taiwan Semiconductor Manufacturing Company Limited', '', '420.39', '-1.19', '-0.28%', '14.276M', '14.091M', '2.18T', '33.15', '+77.92%', '223.70\n479.00']
['CCL', 'Carnival Corporation Ltd.', '', '26.50', '-0.11', '-0.41%', '14.215M', '26.58M', '36.296B', '12.21', '-8.15%', '23.45\n34.03']
['CSGP', 'CoStar Group, Inc.', '', '27.68', '-1.09', '-3.79%', '14.089M', '7.403M', '11.303B', '480.38', '-65.79%', '28.09\n97.43']
['BMY', 'Bristol-Myers Squibb Company', '', '56.95', '-2.39', '-4.03%', '14.056M', '11.572M', '116.296B', '16.61', '+27.81%', '42.52\n62.89']
['RIOT', 'Riot Platforms, Inc.', '', '20.19', '0.00', '0.00%', '13.881M', '17.686M', '7.635B', '--', '+66.86%', '10.59\n30.32']
['AVGO', 'Broadcom Inc.', '', '389.11', '+5.06', '+1.32%', '13.836M', '26.401M', '1.851T', '63.92', '+36.70%', '273.00\n495.00']
['KO', 'The Coca-Cola Company', '', '83.08', '-1.17', '-1.39%', '13.775M', '16.869M', '357.45B', '26.49', '+21.47%', '65.35\n85.68']
['TTD', 'The Trade Desk, Inc.', '', '18.94', '-0.85', '-4.30%', '13.739M', '19.634M', '8.904B', '22.31', '-75.39%', '16.98\n91.45']
['VG', 'Venture Global, Inc.', '', '13.23', '-0.13', '-0.97%', '13.706M', '16.965M', '32.868B', '14.84', '-19.32%', '5.72\n17.62']
['RKLB', 'Rocket Lab Corporation', '', '78.81', '+2.08', '+2.71%', '13.681M', '27.551M', '49.242B', '--', '+72.04%', '37.57\n151.00']
['S', 'SentinelOne, Inc.', '', '19.92', '+1.37', '+7.39%', '13.525M', '7.876M', '6.802B', '--', '+5.22%', '11.81\n21.40']
['CRM', 'Salesforce, Inc.', '', '167.56', '-3.66', '-2.14%', '13.508M', '14.976M', '137.232B', '19.88', '-33.53%', '146.32\n274.00']
['GOOGL', 'Alphabet Inc.', '', '359.51', '+7.00', '+1.99%', '13.393M', '31.503M', '4.387T', '26.89', '+93.69%', '180.48\n408.61']
['AVTR', 'Avantor, Inc.', '', '11.29', '+0.73', '+6.91%', '13.328M', '9.67M', '7.708B', '--', '-17.63%', '7.27\n15.93']
['RDW', 'Redwire Corporation', '', '9.74', '+0.15', '+1.56%', '13.267M', '40.134M', '2.326B', '--', '-43.52%', '4.87\n26.64']
['UMC', 'United Microelectronics Corporation', '', '23.84', '+0.38', '+1.62%', '13.176M', '17.332M', '59.821B', '38.58', '+213.64%', '6.56\n28.96']
['LPL', 'LG Display Co., Ltd.', '', '3.51', '-0.08', '-2.23%', '13.169M', '2.203M', '3.51B', '--', '+4.66%', '3.34\n5.83']
['NKE', 'NIKE, Inc.', '', '42.86', '-0.90', '-2.06%', '13.09M', '23.768M', '63.471B', '20.84', '-39.21%', '40.00\n80.17']
['PR', 'Permian Resources Corporation', '', '19.59', '-0.03', '-0.15%', '13.079M', '11.56M', '16.402B', '22.81', '+44.90%', '11.92\n22.68']
['PBR', 'Petróleo Brasileiro S.A. - Petrobras', '', '17.92', '+0.04', '+0.22%', '13.028M', '17M', '115.483B', '4.87', '+43.04%', '11.43\n22.24']
['CLF', 'Cleveland-Cliffs Inc.', '', '9.79', '+0.08', '+0.82%', '12.908M', '19.078M', '5.584B', '--', '+7.06%', '7.73\n16.70']
['QCOM', 'QUALCOMM Incorporated', '', '178.10', '-5.88', '-3.20%', '12.771M', '23.471M', '187.717B', '20.10', '+19.24%', '121.99\n259.92']
['OWL', 'Blue Owl Capital Inc.', '', '9.62', '+0.33', '+3.55%', '12.733M', '26.493M', '6.501B', '77.88', '-50.61%', '7.95\n21.08']
['ABT', 'Abbott Laboratories', '', '88.96', '-3.15', '-3.42%', '12.474M', '13.315M', '154.952B', '25.80', '-29.95%', '81.97\n137.49']
['DKNG', 'DraftKings Inc.', '', '25.21', '-1.24', '-4.69%', '12.373M', '12.41M', '12.507B', '288.77', '-39.61%', '20.46\n48.78']
['STM', 'STMicroelectronics N.V.', '', '70.13', '+1.66', '+2.42%', '12.341M', '12.669M', '62.584B', '436.76', '+117.23%', '21.11\n81.42']
['GEHC', 'GE HealthCare Technologies Inc.', '', '61.66', '-3.65', '-5.59%', '12.142M', '5.228M', '28.049B', '14.64', '-12.21%', '58.75\n89.77']
['ATAI', 'AtaiBeckley Inc.', '', '5.67', '+0.70', '+14.08%', '11.813M', '7.774M', '2.088B', '--', '+87.55%', '2.58\n6.75']
['FCX', 'Freeport-McMoRan Inc.', '', '61.95', '+1.98', '+3.30%', '11.628M', '14.941M', '89.057B', '31.73', '+35.92%', '35.15\n72.28']
['GIS', 'General Mills, Inc.', '', '36.46', '-0.14', '-0.38%', '11.517M', '10.122M', '19.459B', '--', '-26.81%', '31.75\n51.68']
['FPS', 'Forgent Power Solutions, Inc.', '', '41.18', '-1.42', '-3.33%', '11.441M', '6.853M', '10.706B', '643.84', '+46.90%', '25.95\n66.00']
['META', 'Meta Platforms, Inc.', '', '661.04', '+4.31', '+0.66%', '11.431M', '17.918M', '1.678T', '23.89', '-7.55%', '520.26\n796.25']
['CVS', 'CVS Health Corporation', '', '106.18', '+0.28', '+0.26%', '11.396M', '8.267M', '135.478B', '46.13', '+65.62%', '58.50\n106.40']
['CSX', 'CSX Corporation', '', '49.92', '+0.28', '+0.56%', '11.197M', '12.418M', '92.758B', '30.44', '+48.27%', '31.80\n49.90']
['OXY', 'Occidental Petroleum Corporation', '', '54.57', '-0.24', '-0.44%', '11.115M', '11.289M', '54.277B', '74.09', '+28.39%', '38.80\n67.45']
['GGB', 'Gerdau S.A.', '', '4.61', '+0.12', '+2.67%', '10.864M', '17.893M', '9.05B', '27.80', '+53.24%', '2.83\n4.98']
['ERAS', 'Erasca, Inc.', '', '19.50', '+1.60', '+8.94%', '10.705M', '6.839M', '6.064B', '--', '+1,169.50%', '1.33\n24.28']
['NEE', 'NextEra Energy, Inc.', '', '89.54', '+1.16', '+1.31%', '10.678M', '11.631M', '186.745B', '22.44', '+18.31%', '69.24\n98.75']
['BULL', 'Webull Corporation', '', '7.53', '+0.25', '+3.43%', '10.674M', '13.719M', '4.005B', '--', '-39.98%', '4.50\n18.32']
['CRWD', 'CrowdStrike Holdings, Inc.', '', '210.73', '+22.82', '+12.14%', '10.605M', '12.569M', '214.578B', '--', '+58.82%', '85.68\n209.50']
['LUNR', 'Intuitive Machines, Inc.', '', '14.91', '-0.24', '-1.58%', '10.474M', '14.121M', '2.392B', '--', '+36.73%', '7.78\n46.75']
['SEI', 'Solaris Energy Infrastructure, Inc.', '', '69.50', '+2.35', '+3.50%', '10.444M', '2.382M', '4.259B', '77.76', '+120.96%', '24.57\n86.19']
['AXTI', 'AXT, Inc.', '', '57.57', '+7.11', '+14.09%', '10.303M', '10.566M', '3.766B', '--', '+2,038.14%', '1.85\n143.16']
['FRSH', 'Freshworks Inc.', '', '10.47', '-0.36', '-3.32%', '10.285M', '17.133M', '2.894B', '17.25', '-21.46%', '6.79\n15.06']
['MCHP', 'Microchip Technology Incorporated', '', '87.11', '+2.88', '+3.42%', '10.239M', '11.929M', '47.301B', '383.15', '+15.21%', '48.52\n105.91']
['BP', 'BP p.l.c.', '', '41.40', '+0.57', '+1.40%', '10.193M', '9.637M', '106.61B', '33.28', '+28.15%', '31.59\n48.27']
['NTSK', 'Netskope, Inc.', '', '14.27', '+1.47', '+11.48%', '10.155M', '5.539M', '5.764B', '--', '-43.09%', '7.67\n27.99']
['KHC', 'The Kraft Heinz Company', '', '25.08', '-0.15', '-0.59%', '10.126M', '13.988M', '29.739B', '--', '-6.97%', '21.04\n29.19']
['NVTS', 'Navitas Semiconductor Corporation', '', '13.09', '+0.22', '+1.71%', '9.957M', '33.84M', '3.188B', '--', '+106.58%', '5.44\n34.17']

In [30]:
data

[{'name': 'Nu Holdings Ltd.',
  'symbol': 'NU',
  'price': '13.99',
  'change': '+0.32',
  'volume': '152.753M',
  'market_cap': '67.578B',
  'pe_ratio': '21.09'},
 {'name': 'American Airlines Group Inc.',
  'symbol': 'AAL',
  'price': '15.67',
  'change': '-0.64',
  'volume': '133.164M',
  'market_cap': '10.364B',
  'pe_ratio': '53.33'},
 {'name': 'SK hynix Inc.',
  'symbol': 'SKHYV',
  'price': '168.01',
  'change': '+168.01',
  'volume': '107.675M',
  'market_cap': '1.193T',
  'pe_ratio': '--'},
 {'name': 'Ondas Inc.',
  'symbol': 'ONDS',
  'price': '7.36',
  'change': '+0.40',
  'volume': '103.149M',
  'market_cap': '4.194B',
  'pe_ratio': '15.91'},
 {'name': 'NVIDIA Corporation',
  'symbol': 'NVDA',
  'price': '211.80',
  'change': '+8.27',
  'volume': '102.209M',
  'market_cap': '5.13T',
  'pe_ratio': '31.17'},
 {'name': 'Opendoor Technologies Inc.',
  'symbol': 'OPEN',
  'price': '4.55',
  'change': '+0.07',
  'volume': '98.083M',
  'market_cap': '4.39B',
  'pe_ratio': '--'},
 {'name': 'Nokia Oyj',
  'symbol': 'NOK',
  'price': '11.70',
  'change': '+0.01',
  'volume': '87.515M',
  'market_cap': '65.316B',
  'pe_ratio': '76.29'},
 {'name': 'UiPath, Inc.',
  'symbol': 'PATH',
  'price': '11.94',
  'change': '+0.09',
  'volume': '85.807M',
  'market_cap': '6.186B',
  'pe_ratio': '19.60'},
 {'name': 'SoFi Technologies, Inc.',
  'symbol': 'SOFI',
  'price': '18.55',
  'change': '+0.42',
  'volume': '84.128M',
  'market_cap': '23.795B',
  'pe_ratio': '40.75'},
 {'name': 'Intel Corporation',
  'symbol': 'INTC',
  'price': '107.76',
  'change': '+4.64',
  'volume': '81.729M',
  'market_cap': '541.602B',
  'pe_ratio': '--'},
 {'name': 'CleanSpark, Inc.',
  'symbol': 'CLSK',
  'price': '13.45',
  'change': '+1.09',
  'volume': '74.001M',
  'market_cap': '3.451B',
  'pe_ratio': '--'},
 {'name': 'International Business Machines Corporation',
  'symbol': 'IBM',
  'price': '217.07',
  'change': '-73.16',
  'volume': '67.423M',
  'market_cap': '204.021B',
  'pe_ratio': '25.71'},
 {'name': 'SK hynix Inc.',
  'symbol': 'SKHY',
  'price': '193.92',
  'change': '+41.57',
  'volume': '66.814M',
  'market_cap': '1.377T',
  'pe_ratio': '--'},
 {'name': 'TeraWulf Inc.',
  'symbol': 'WULF',
  'price': '19.41',
  'change': '-1.48',
  'volume': '57.849M',
  'market_cap': '9.618B',
  'pe_ratio': '--'},
 {'name': 'MARA Holdings, Inc.',
  'symbol': 'MARA',
  'price': '12.16',
  'change': '-0.03',
  'volume': '57.195M',
  'market_cap': '4.636B',
  'pe_ratio': '--'},
 {'name': 'AT&T Inc.',
  'symbol': 'T',
  'price': '21.28',
  'change': '-0.27',
  'volume': '53.555M',
  'market_cap': '147.861B',
  'pe_ratio': '7.20'},
 {'name': 'Oracle Corporation',
  'symbol': 'ORCL',
  'price': '127.94',
  'change': '-3.60',
  'volume': '52.648M',
  'market_cap': '368.527B',
  'pe_ratio': '22.56'},
 {'name': 'Bitmine Immersion Technologies, Inc.',
  'symbol': 'BMNR',
  'price': '16.29',
  'change': '+1.68',
  'volume': '51.549M',
  'market_cap': '9.278B',
  'pe_ratio': '--'},
 {'name': 'Bank of America Corporation',
  'symbol': 'BAC',
  'price': '60.62',
  'change': '+1.12',
  'volume': '49.432M',
  'market_cap': '430.195B',
  'pe_ratio': '--'},
 {'name': 'Joby Aviation, Inc.',
  'symbol': 'JOBY',
  'price': '7.89',
  'change': '+0.41',
  'volume': '49.054M',
  'market_cap': '7.761B',
  'pe_ratio': '--'},
 {'name': 'Palantir Technologies Inc.',
  'symbol': 'PLTR',
  'price': '133.72',
  'change': '+3.68',
  'volume': '45.485M',
  'market_cap': '320.569B',
  'pe_ratio': '146.18'},
 {'name': 'Space Exploration Technologies Corp.',
  'symbol': 'SPCX',
  'price': '136.08',
  'change': '-3.06',
  'volume': '43.495M',
  'market_cap': '1.793T',
  'pe_ratio': '--'},
 {'name': 'Ford Motor Company',
  'symbol': 'F',
  'price': '13.94',
  'change': '+0.09',
  'volume': '42.722M',
  'market_cap': '55.547B',
  'pe_ratio': '--'},
 {'name': 'Banco Bradesco S.A.',
  'symbol': 'BBD',
  'price': '3.63',
  'change': '+0.02',
  'volume': '42.618M',
  'market_cap': '38.372B',
  'pe_ratio': '8.54'},
 {'name': 'Pfizer Inc.',
  'symbol': 'PFE',
  'price': '24.25',
  'change': '-0.23',
  'volume': '40.862M',
  'market_cap': '138.212B',
  'pe_ratio': '18.68'},
 {'name': 'Plug Power Inc.',
  'symbol': 'PLUG',
  'price': '2.27',
  'change': '+0.10',
  'volume': '40.712M',
  'market_cap': '3.167B',
  'pe_ratio': '--'},
 {'name': 'Telefonaktiebolaget LM Ericsson (publ)',
  'symbol': 'ERIC',
  'price': '10.14',
  'change': '-1.58',
  'volume': '39.448M',
  'market_cap': '33.48B',
  'pe_ratio': '--'},
 {'name': 'Wells Fargo & Company',
  'symbol': 'WFC',
  'price': '85.29',
  'change': '-2.38',
  'volume': '38.943M',
  'market_cap': '261.004B',
  'pe_ratio': '--'},
 {'name': 'Transocean Ltd.',
  'symbol': 'RIG',
  'price': '5.31',
  'change': '-0.06',
  'volume': '37.61M',
  'market_cap': '5.877B',
  'pe_ratio': '--'},
 {'name': 'IREN Limited',
  'symbol': 'IREN',
  'price': '38.59',
  'change': '-0.39',
  'volume': '34.939M',
  'market_cap': '13.791B',
  'pe_ratio': '71.76'},
 {'name': 'Apple Inc.',
  'symbol': 'AAPL',
  'price': '314.86',
  'change': '-2.45',
  'volume': '34.499M',
  'market_cap': '4.624T',
  'pe_ratio': '38.47'},
 {'name': 'Figma, Inc.',
  'symbol': 'FIG',
  'price': '23.86',
  'change': '+0.21',
  'volume': '33.219M',
  'market_cap': '12.607B',
  'pe_ratio': '--'},
 {'name': 'SoundHound AI, Inc.',
  'symbol': 'SOUN',
  'price': '6.69',
  'change': '+0.20',
  'volume': '32.492M',
  'market_cap': '2.915B',
  'pe_ratio': '--'},
 {'name': 'Citigroup Inc.',
  'symbol': 'C',
  'price': '133.27',
  'change': '-7.44',
  'volume': '32.124M',
  'market_cap': '227.302B',
  'pe_ratio': '--'},
 {'name': 'Grab Holdings Limited',
  'symbol': 'GRAB',
  'price': '3.80',
  'change': '-0.14',
  'volume': '31.802M',
  'market_cap': '15.542B',
  'pe_ratio': '101.30'},
 {'name': 'Micron Technology, Inc.',
  'symbol': 'MU',
  'price': '983.12',
  'change': '+46.12',
  'volume': '30.387M',
  'market_cap': '1.11T',
  'pe_ratio': '21.15'},
 {'name': 'Hecla Mining Company',
  'symbol': 'HL',
  'price': '15.50',
  'change': '+0.25',
  'volume': '30.188M',
  'market_cap': '10.396B',
  'pe_ratio': '22.17'},
 {'name': 'Snap Inc.',
  'symbol': 'SNAP',
  'price': '4.68',
  'change': '+0.02',
  'volume': '29.933M',
  'market_cap': '7.756B',
  'pe_ratio': '--'},
 {'name': 'Coupang, Inc.',
  'symbol': 'CPNG',
  'price': '17.74',
  'change': '-0.18',
  'volume': '29.012M',
  'market_cap': '31.844B',
  'pe_ratio': '--'},
 {'name': 'Netflix, Inc.',
  'symbol': 'NFLX',
  'price': '73.53',
  'change': '-0.30',
  'volume': '28.473M',
  'market_cap': '309.62B',
  'pe_ratio': '23.85'},
 {'name': 'Archer Aviation Inc.',
  'symbol': 'ACHR',
  'price': '4.85',
  'change': '+0.30',
  'volume': '28.414M',
  'market_cap': '3.7B',
  'pe_ratio': '--'},
 {'name': 'QXO, Inc.',
  'symbol': 'QXO',
  'price': '14.46',
  'change': '+0.57',
  'volume': '28.16M',
  'market_cap': '15.007B',
  'pe_ratio': '--'},
 {'name': 'Microsoft Corporation',
  'symbol': 'MSFT',
  'price': '384.93',
  'change': '-6.06',
  'volume': '26.895M',
  'market_cap': '2.859T',
  'pe_ratio': '23.29'},
 {'name': 'Rivian Automotive, Inc.',
  'symbol': 'RIVN',
  'price': '17.50',
  'change': '+0.19',
  'volume': '26.701M',
  'market_cap': '25.329B',
  'pe_ratio': '--'},
 {'name': 'Rocket Companies, Inc.',
  'symbol': 'RKT',
  'price': '14.30',
  'change': '+0.39',
  'volume': '26.585M',
  'market_cap': '40.461B',
  'pe_ratio': '547.98'},
 {'name': 'Comcast Corporation',
  'symbol': 'CMCSA',
  'price': '23.19',
  'change': '-0.78',
  'volume': '26.067M',
  'market_cap': '82.84B',
  'pe_ratio': '4.68'},
 {'name': 'Stellantis N.V.',
  'symbol': 'STLA',
  'price': '5.69',
  'change': '+0.12',
  'volume': '24.798M',
  'market_cap': '16.487B',
  'pe_ratio': '--'},
 {'name': 'Denison Mines Corp.',
  'symbol': 'DNN',
  'price': '3.17',
  'change': '+0.14',
  'volume': '24.736M',
  'market_cap': '2.869B',
  'pe_ratio': '--'},
 {'name': 'Keel Infrastructure Corp.',
  'symbol': 'KEEL',
  'price': '4.49',
  'change': '+0.13',
  'volume': '24.573M',
  'market_cap': '2.711B',
  'pe_ratio': '--'},
 {'name': 'NuScale Power Corporation',
  'symbol': 'SMR',
  'price': '8.60',
  'change': '+0.25',
  'volume': '24.042M',
  'market_cap': '2.977B',
  'pe_ratio': '--'},
 {'name': 'Vale S.A.',
  'symbol': 'VALE',
  'price': '14.59',
  'change': '+0.41',
  'volume': '23.954M',
  'market_cap': '62.092B',
  'pe_ratio': '19.96'},
 {'name': 'Infosys Limited',
  'symbol': 'INFY',
  'price': '11.05',
  'change': '-0.45',
  'volume': '23.875M',
  'market_cap': '44.741B',
  'pe_ratio': '14.40'},
 {'name': 'Amazon.com, Inc.',
  'symbol': 'AMZN',
  'price': '247.49',
  'change': '+0.18',
  'volume': '23.406M',
  'market_cap': '2.662T',
  'pe_ratio': '29.58'},
 {'name': 'ServiceNow, Inc.',
  'symbol': 'NOW',
  'price': '104.85',
  'change': '-6.41',
  'volume': '23.21M',
  'market_cap': '108.133B',
  'pe_ratio': '66.23'},
 {'name': 'NIO Inc.',
  'symbol': 'NIO',
  'price': '5.01',
  'change': '+0.08',
  'volume': '23.114M',
  'market_cap': '12.553B',
  'pe_ratio': '--'},
 {'name': 'Tesla, Inc.',
  'symbol': 'TSLA',
  'price': '396.18',
  'change': '+1.42',
  'volume': '22.671M',
  'market_cap': '1.488T',
  'pe_ratio': '362.40'},
 {'name': 'BlackBerry Limited',
  'symbol': 'BB',
  'price': '11.01',
  'change': '+0.30',
  'volume': '22.239M',
  'market_cap': '6.453B',
  'pe_ratio': '110.55'},
 {'name': 'Super Micro Computer, Inc.',
  'symbol': 'SMCI',
  'price': '27.65',
  'change': '-0.01',
  'volume': '21.898M',
  'market_cap': '17.886B',
  'pe_ratio': '14.50'},
 {'name': 'Warner Bros. Discovery, Inc.',
  'symbol': 'WBD',
  'price': '27.48',
  'change': '+0.39',
  'volume': '21.76M',
  'market_cap': '68.896B',
  'pe_ratio': '--'},
 {'name': 'Cisco Systems, Inc.',
  'symbol': 'CSCO',
  'price': '117.09',
  'change': '-2.16',
  'volume': '21.344M',
  'market_cap': '461.503B',
  'pe_ratio': '39.75'},
 {'name': 'Fastenal Company',
  'symbol': 'FAST',
  'price': '45.74',
  'change': '-1.31',
  'volume': '20.524M',
  'market_cap': '52.511B',
  'pe_ratio': '--'},
 {'name': 'Aurora Innovation, Inc.',
  'symbol': 'AUR',
  'price': '6.13',
  'change': '+0.08',
  'volume': '20.422M',
  'market_cap': '12.022B',
  'pe_ratio': '--'},
 {'name': 'Wipro Limited',
  'symbol': 'WIT',
  'price': '1.84',
  'change': '-0.06',
  'volume': '20.365M',
  'market_cap': '18.201B',
  'pe_ratio': '14.20'},
 {'name': 'Baytex Energy Corp.',
  'symbol': 'BTE',
  'price': '4.24',
  'change': '+0.03',
  'volume': '20.201M',
  'market_cap': '3.021B',
  'pe_ratio': '--'},
 {'name': 'Boston Scientific Corporation',
  'symbol': 'BSX',
  'price': '42.63',
  'change': '-2.02',
  'volume': '20.088M',
  'market_cap': '63.363B',
  'pe_ratio': '18.68'},
 {'name': 'Marvell Technology, Inc.',
  'symbol': 'MRVL',
  'price': '222.44',
  'change': '+4.91',
  'volume': '20.012M',
  'market_cap': '199.65B',
  'pe_ratio': '75.14'},
 {'name': 'CoreWeave, Inc.',
  'symbol': 'CRWV',
  'price': '79.94',
  'change': '-3.37',
  'volume': '19.758M',
  'market_cap': '43.613B',
  'pe_ratio': '--'},
 {'name': 'Kenvue Inc.',
  'symbol': 'KVUE',
  'price': '18.76',
  'change': '-0.47',
  'volume': '19.474M',
  'market_cap': '36.019B',
  'pe_ratio': '22.89'},
 {'name': 'Fermi Inc.',
  'symbol': 'FRMI',
  'price': '6.74',
  'change': '+0.43',
  'volume': '19.241M',
  'market_cap': '4.301B',
  'pe_ratio': '--'},
 {'name': 'QuantumScape Corporation',
  'symbol': 'QS',
  'price': '6.42',
  'change': '+0.14',
  'volume': '19.138M',
  'market_cap': '3.949B',
  'pe_ratio': '--'},
 {'name': 'HP Inc.',
  'symbol': 'HPQ',
  'price': '24.63',
  'change': '-0.14',
  'volume': '18.983M',
  'market_cap': '22.525B',
  'pe_ratio': '9.15'},
 {'name': 'Advanced Micro Devices, Inc.',
  'symbol': 'AMD',
  'price': '548.13',
  'change': '+13.74',
  'volume': '18.876M',
  'market_cap': '893.781B',
  'pe_ratio': '178.20'},
 {'name': 'Cipher Digital Inc.',
  'symbol': 'CIFR',
  'price': '19.87',
  'change': '-0.22',
  'volume': '18.875M',
  'market_cap': '8.128B',
  'pe_ratio': '--'},
 {'name': 'Uber Technologies, Inc.',
  'symbol': 'UBER',
  'price': '72.08',
  'change': '-2.18',
  'volume': '18.702M',
  'market_cap': '146.726B',
  'pe_ratio': '18.36'},
 {'name': 'B2Gold Corp.',
  'symbol': 'BTG',
  'price': '3.79',
  'change': '+0.01',
  'volume': '18.631M',
  'market_cap': '5.05B',
  'pe_ratio': '10.07'},
 {'name': 'Ultrapar Participações S.A.',
  'symbol': 'UGP',
  'price': '5.94',
  'change': '-0.06',
  'volume': '18.324M',
  'market_cap': '6.349B',
  'pe_ratio': '10.53'},
 {'name': 'Rigetti Computing, Inc.',
  'symbol': 'RGTI',
  'price': '16.11',
  'change': '+0.75',
  'volume': '18.272M',
  'market_cap': '5.355B',
  'pe_ratio': '--'},
 {'name': 'Lloyds Banking Group plc',
  'symbol': 'LYG',
  'price': '5.93',
  'change': '+0.04',
  'volume': '18.218M',
  'market_cap': '86.168B',
  'pe_ratio': '14.53'},
 {'name': 'Ambev S.A.',
  'symbol': 'ABEV',
  'price': '3.09',
  'change': '+0.03',
  'volume': '18.134M',
  'market_cap': '47.749B',
  'pe_ratio': '15.92'},
 {'name': 'Strategy Inc',
  'symbol': 'MSTR',
  'price': '97.58',
  'change': '+5.48',
  'volume': '17.706M',
  'market_cap': '35.381B',
  'pe_ratio': '--'},
 {'name': 'Chipotle Mexican Grill, Inc.',
  'symbol': 'CMG',
  'price': '36.43',
  'change': '-0.20',
  'volume': '17.566M',
  'market_cap': '46.73B',
  'pe_ratio': '33.57'},
 {'name': 'Verizon Communications Inc.',
  'symbol': 'VZ',
  'price': '42.47',
  'change': '-0.21',
  'volume': '17.515M',
  'market_cap': '177.336B',
  'pe_ratio': '10.39'},
 {'name': 'IonQ, Inc.',
  'symbol': 'IONQ',
  'price': '39.29',
  'change': '+0.41',
  'volume': '17.283M',
  'market_cap': '14.666B',
  'pe_ratio': '42.20'},
 {'name': 'Hewlett Packard Enterprise Company',
  'symbol': 'HPE',
  'price': '49.56',
  'change': '+2.32',
  'volume': '17.133M',
  'market_cap': '65.628B',
  'pe_ratio': '44.08'},
 {'name': 'Conagra Brands, Inc.',
  'symbol': 'CAG',
  'price': '14.15',
  'change': '-0.18',
  'volume': '16.852M',
  'market_cap': '6.77B',
  'pe_ratio': '--'},
 {'name': 'Coeur Mining, Inc.',
  'symbol': 'CDE',
  'price': '16.00',
  'change': '+0.41',
  'volume': '16.67M',
  'market_cap': '16.489B',
  'pe_ratio': '12.89'},
 {'name': 'Nebius Group N.V.',
  'symbol': 'NBIS',
  'price': '194.09',
  'change': '-16.42',
  'volume': '16.577M',
  'market_cap': '49.279B',
  'pe_ratio': '72.79'},
 {'name': 'Robinhood Markets, Inc.',
  'symbol': 'HOOD',
  'price': '113.45',
  'change': '+3.59',
  'volume': '16.257M',
  'market_cap': '102.162B',
  'pe_ratio': '53.35'},
 {'name': 'ExxonMobil Holdings Corporation',
  'symbol': 'XOM',
  'price': '145.09',
  'change': '+0.58',
  'volume': '16.096M',
  'market_cap': '601.39B',
  'pe_ratio': '24.33'},
 {'name': 'Applied Digital Corporation',
  'symbol': 'APLD',
  'price': '28.47',
  'change': '-0.37',
  'volume': '16.021M',
  'market_cap': '8.136B',
  'pe_ratio': '--'},
 {'name': 'Circle Internet Group',
  'symbol': 'CRCL',
  'price': '63.22',
  'change': '+0.22',
  'volume': '15.793M',
  'market_cap': '15.715B',
  'pe_ratio': '--'},
 {'name': 'D-Wave Quantum Inc.',
  'symbol': 'QBTS',
  'price': '18.95',
  'change': '+0.29',
  'volume': '15.664M',
  'market_cap': '7.02B',
  'pe_ratio': '--'},
 {'name': 'Catalyst Pharmaceuticals, Inc.',
  'symbol': 'CPRX',
  'price': '31.49',
  'change': '+0.01',
  'volume': '15.514M',
  'market_cap': '3.855B',
  'pe_ratio': '18.20'},
 {'name': 'Huntington Bancshares Incorporated',
  'symbol': 'HBAN',
  'price': '17.85',
  'change': '-0.08',
  'volume': '14.903M',
  'market_cap': '36.184B',
  'pe_ratio': '13.99'},
 {'name': 'Itaú Unibanco Holding S.A.',
  'symbol': 'ITUB',
  'price': '8.55',
  'change': '+0.08',
  'volume': '14.811M',
  'market_cap': '94.237B',
  'pe_ratio': '10.57'},
 {'name': 'PG&E Corporation',
  'symbol': 'PCG',
  'price': '17.44',
  'change': '+0.07',
  'volume': '14.8M',
  'market_cap': '38.407B',
  'pe_ratio': '13.48'},
 {'name': 'Walmart Inc.',
  'symbol': 'WMT',
  'price': '113.70',
  'change': '-1.08',
  'volume': '14.682M',
  'market_cap': '904.834B',
  'pe_ratio': '40.41'},
 {'name': 'JPMorgan Chase & Co.',
  'symbol': 'JPM',
  'price': '342.89',
  'change': '+8.36',
  'volume': '14.537M',
  'market_cap': '918.778B',
  'pe_ratio': '--'},
 {'name': 'Keurig Dr Pepper Inc.',
  'symbol': 'KDP',
  'price': '30.26',
  'change': '-0.99',
  'volume': '14.47M',
  'market_cap': '41.171B',
  'pe_ratio': '23.18'},
 {'name': 'AGNC Investment Corp.',
  'symbol': 'AGNC',
  'price': '11.18',
  'change': '+0.19',
  'volume': '14.373M',
  'market_cap': '12.834B',
  'pe_ratio': '9.11'},
 {'name': 'Taiwan Semiconductor Manufacturing Company Limited',
  'symbol': 'TSM',
  'price': '420.39',
  'change': '-1.19',
  'volume': '14.276M',
  'market_cap': '2.18T',
  'pe_ratio': '33.15'},
 {'name': 'Carnival Corporation Ltd.',
  'symbol': 'CCL',
  'price': '26.50',
  'change': '-0.11',
  'volume': '14.215M',
  'market_cap': '36.296B',
  'pe_ratio': '12.21'},
 {'name': 'CoStar Group, Inc.',
  'symbol': 'CSGP',
  'price': '27.68',
  'change': '-1.09',
  'volume': '14.089M',
  'market_cap': '11.303B',
  'pe_ratio': '480.38'},
 {'name': 'Bristol-Myers Squibb Company',
  'symbol': 'BMY',
  'price': '56.95',
  'change': '-2.39',
  'volume': '14.056M',
  'market_cap': '116.296B',
  'pe_ratio': '16.61'},
 {'name': 'Riot Platforms, Inc.',
  'symbol': 'RIOT',
  'price': '20.19',
  'change': '0.00',
  'volume': '13.881M',
  'market_cap': '7.635B',
  'pe_ratio': '--'},
 {'name': 'Broadcom Inc.',
  'symbol': 'AVGO',
  'price': '389.11',
  'change': '+5.06',
  'volume': '13.836M',
  'market_cap': '1.851T',
  'pe_ratio': '63.92'},
 {'name': 'The Coca-Cola Company',
  'symbol': 'KO',
  'price': '83.08',
  'change': '-1.17',
  'volume': '13.775M',
  'market_cap': '357.45B',
  'pe_ratio': '26.49'},
 {'name': 'The Trade Desk, Inc.',
  'symbol': 'TTD',
  'price': '18.94',
  'change': '-0.85',
  'volume': '13.739M',
  'market_cap': '8.904B',
  'pe_ratio': '22.31'},
 {'name': 'Venture Global, Inc.',
  'symbol': 'VG',
  'price': '13.23',
  'change': '-0.13',
  'volume': '13.706M',
  'market_cap': '32.868B',
  'pe_ratio': '14.84'},
 {'name': 'Rocket Lab Corporation',
  'symbol': 'RKLB',
  'price': '78.81',
  'change': '+2.08',
  'volume': '13.681M',
  'market_cap': '49.242B',
  'pe_ratio': '--'},
 {'name': 'SentinelOne, Inc.',
  'symbol': 'S',
  'price': '19.92',
  'change': '+1.37',
  'volume': '13.525M',
  'market_cap': '6.802B',
  'pe_ratio': '--'},
 {'name': 'Salesforce, Inc.',
  'symbol': 'CRM',
  'price': '167.56',
  'change': '-3.66',
  'volume': '13.508M',
  'market_cap': '137.232B',
  'pe_ratio': '19.88'},
 {'name': 'Alphabet Inc.',
  'symbol': 'GOOGL',
  'price': '359.51',
  'change': '+7.00',
  'volume': '13.393M',
  'market_cap': '4.387T',
  'pe_ratio': '26.89'},
 {'name': 'Avantor, Inc.',
  'symbol': 'AVTR',
  'price': '11.29',
  'change': '+0.73',
  'volume': '13.328M',
  'market_cap': '7.708B',
  'pe_ratio': '--'},
 {'name': 'Redwire Corporation',
  'symbol': 'RDW',
  'price': '9.74',
  'change': '+0.15',
  'volume': '13.267M',
  'market_cap': '2.326B',
  'pe_ratio': '--'},
 {'name': 'United Microelectronics Corporation',
  'symbol': 'UMC',
  'price': '23.84',
  'change': '+0.38',
  'volume': '13.176M',
  'market_cap': '59.821B',
  'pe_ratio': '38.58'},
 {'name': 'LG Display Co., Ltd.',
  'symbol': 'LPL',
  'price': '3.51',
  'change': '-0.08',
  'volume': '13.169M',
  'market_cap': '3.51B',
  'pe_ratio': '--'},
 {'name': 'NIKE, Inc.',
  'symbol': 'NKE',
  'price': '42.86',
  'change': '-0.90',
  'volume': '13.09M',
  'market_cap': '63.471B',
  'pe_ratio': '20.84'},
 {'name': 'Permian Resources Corporation',
  'symbol': 'PR',
  'price': '19.59',
  'change': '-0.03',
  'volume': '13.079M',
  'market_cap': '16.402B',
  'pe_ratio': '22.81'},
 {'name': 'Petróleo Brasileiro S.A. - Petrobras',
  'symbol': 'PBR',
  'price': '17.92',
  'change': '+0.04',
  'volume': '13.028M',
  'market_cap': '115.483B',

In [31]:
len(data)

332

In [100]:
stocks_df=(
    pd
    .DataFrame(data)
    .apply(lambda col: col.str.strip() if col.dtype == "object" else col)
    
    # extract the other things without numbers and dot
    # .price.str.extract(r"([^0-9.])", expand=False).unique()
    # .price.str.replace(",", "", regex=False)
    # .apply(lambda col: col.str.replace(",", "", regex=False) if col.dtype == "object" else col)
    # .price.str.extract(r"([^0-9.])", expand=False).unique()
    
    
    .assign(
        price=lambda df: df.price.str.replace(",",""),
        change=lambda df: df.change.str.replace("+",""),
        volume= lambda df: df.volume.str.replace("M",""),
        market_cap= lambda df: df.market_cap.apply(lambda val: float(val.replace("B","")) if "B" in val else float(val.replace("T",""))*1000),
        pe_ratio= lambda df: df.pe_ratio.replace("--",np.nan).str.replace(",","")
    )
    # transform columns object to numeric
    .assign(
        price=lambda df: pd.to_numeric(df.price),
        change=lambda df: pd.to_numeric(df.change),
        volume=lambda df: pd.to_numeric(df.volume),
        pe_ratio=lambda df: pd.to_numeric(df.pe_ratio)
    )
    
    # rename the price column
    .rename(
        columns={
            "price":"price_usd",
            "volume":"volume_in_million",
            "market_cap":"market_cap_in_billion"
        }
    )
)

stocks_df

,name,symbol,price_usd,change,volume_in_million,market_cap_in_billion,pe_ratio
0,Nu Holdings Ltd.,NU,13.99,0.32,152.753,67.578,21.09
1,American Airlines Group Inc.,AAL,15.67,-0.64,133.164,10.364,53.33
2,SK hynix Inc.,SKHYV,168.01,168.01,107.675,1193.000,NaN
3,Ondas Inc.,ONDS,7.36,0.40,103.149,4.194,15.91
4,NVIDIA Corporation,NVDA,211.80,8.27,102.209,5130.000,31.17
...,...,...,...,...,...,...,...
327,Baxter International Inc.,BAX,21.80,-0.77,5.047,11.259,NaN
328,British American Tobacco p.l.c.,BTI,58.20,-0.75,5.033,125.637,12.55
329,Sea Limited,SE,109.29,-1.37,5.027,66.938,43.57
330,Almonty Industries Inc.,ALM,15.79,0.77,5.017,4.480,NaN
331,"O'Reilly Automotive, Inc.",ORLY,85.75,-1.53,5.016,71.062,28.41

In [101]:
stocks_df.dtypes

name                      object
symbol                    object
price_usd                float64
change                   float64
volume_in_million        float64
market_cap_in_billion    float64
pe_ratio                 float64
dtype: object

In [67]:
stocks_df.change.str.extract(r"([^0-9.])", expand=False).unique()

array(['+', '-', nan], dtype=object)

There is no need for the `+` sign, so I removed it in the main DataFrame creation code above.

In [77]:
stocks_df.change.str.extract(r"([^0-9.])", expand=False).unique()

array([nan, '-'], dtype=object)

In [80]:
stocks_df.volume.str.extract(r"([^0-9.])", expand=False).unique()

array(['M'], dtype=object)

In [95]:
stocks_df.pe_ratio.str.extract(r"([^0-9.])", expand=False).unique()

array([nan, '-'], dtype=object)

this "-" stands for null values

In [99]:
stocks_df.pe_ratio.str.extract(r"([^0-9.])", expand=False).unique()

array([nan], dtype=object)

In [102]:
stocks_df

,name,symbol,price_usd,change,volume_in_million,market_cap_in_billion,pe_ratio
0,Nu Holdings Ltd.,NU,13.99,0.32,152.753,67.578,21.09
1,American Airlines Group Inc.,AAL,15.67,-0.64,133.164,10.364,53.33
2,SK hynix Inc.,SKHYV,168.01,168.01,107.675,1193.000,NaN
3,Ondas Inc.,ONDS,7.36,0.40,103.149,4.194,15.91
4,NVIDIA Corporation,NVDA,211.80,8.27,102.209,5130.000,31.17
...,...,...,...,...,...,...,...
327,Baxter International Inc.,BAX,21.80,-0.77,5.047,11.259,NaN
328,British American Tobacco p.l.c.,BTI,58.20,-0.75,5.033,125.637,12.55
329,Sea Limited,SE,109.29,-1.37,5.027,66.938,43.57
330,Almonty Industries Inc.,ALM,15.79,0.77,5.017,4.480,NaN
331,"O'Reilly Automotive, Inc.",ORLY,85.75,-1.53,5.016,71.062,28.41

In [107]:
stocks_df.to_excel("yahoo-finance-stocks-data.xlsx",index=False)